### ISSUE TITLE
Keep your bot-token private!

### ISSUE THREAD

**Issue by Androkai** [TJPlaysNow/GameSpaceDiscordBot#5]
Please keep [your bot-token](https://github.com/TJPlaysNow/GameSpaceDiscordBot/blob/master/Discord%20Bot%20-%20GameSpace/src/com/pzg/www/discord/main/Main.java#L14) private! Otherwise, anyone can control your bot.

**Comment by TJPlaysNow** [comment]
Right now the bot is in testing more, it's only on a test server and me and a few devs are working with it, I can refresh it at anytime if needed so thanks, and don't be a meany that makes me change it lol
